version: "3"

services:

  hello-world-nodejs:
    build: ./hello-world-nodejs
    networks:
      - finalproj-net
    ports:
      - "3000:3000"
    restart: on-failure
    depends_on:
      - hello-world-nginx
#    command: ["./wait-for-it.sh", "mq:5672", "-t", "120", "-s", "--", "npm", "start"]

  hello-world-golang:
    build: ./hello-world-golang
    networks:
      - finalproj-net
    ports:
      - "3002:3002"
    restart: on-failure
    depends_on:
      - hello-world-nginx
#    command: ["./wait-for-it.sh", "mq:5672", "-t", "120", "-s", "--", "npm", "start"]

  hello-world-nginx:
    build: ./hello-world-nginx
    networks:
      - finalproj-net
    ports:
      - "80:80"
    restart: on-failure

networks:
  finalproj-net:
    driver: bridge
